config/routes.rb
TimeTrackerApplication::Application.routes.draw do
  resources :timesheets

  resources :employees
 match 'view_timesheet_chart' => 'employees#view_timesheet_chart' , via: [:get, :post]
 match 'chart' => 'employees#chart' , via: [:get, :post]
 match 'report_hours' => 'timesheets#report_hours' , via: [:get, :post]

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base

	has_many :timesheets, :dependent=> :destroy
	def self.find_with_timesheets_in_date_range(id, start_date, end_date)
    conditions="id =? and log_date between ? and ?"
    employee_details_with_timesheets=self.find(:all, :include=>'timesheets', :conditions=> [conditions,id,start_date,end_date], :order=>'log_date asc')
    return employee_details_with_timesheets
end
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
belongs_to :employee, :foreign_key => 'id'

		def self.find_with_timesheets_in_date_range(id, start_date, end_date)
    conditions="id =? and log_date between ? and ?"
    @employee_details_with_timesheets=self.find(:all, :select => "id, hours_spent", :conditions=> [conditions,id,start_date,end_date], :order=>'log_date asc')
    return @employee_details_with_timesheets
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :view_timesheet_chart, :chart]

  # GET /employees
  # GET /employees.json
  

  def view_timesheet_chart 
    start_date= "2013-08-01"
    end_date="2013-11-01"
    @employee_id = params[:id]
    @employee_details_with_timesheets =  Timesheet.find_with_timesheets_in_date_range(@employee_id,start_date,end_date)
    if(!@employee_details_with_timesheets.nil?)
      @employee_details_with_timesheets = @employee_details_with_timesheets[0]
    else
     @employee_details_with_timesheets =nil;
     end

     #render json:@employee_details_with_timesheets

     @h = LazyHighCharts::HighChart.new('bar') do |f|
        f.chart({:defaultSeriesType=>'bar' , :margin=> [50, 200, 60, 170]} )

       #data = {:name=>'Nanda', :data=>[3, 20, 3, 5, 4, 10, 12 ,3, 5,6,7,7,80,9,9]}
        #data =  render @employee_details_with_timesheets.to_json
        
       


    f.series(:name=>'Johnss', :data=>[3, 20, 3, 5, 4, 10, 12 ,3, 5,6,7,7,80,9,9])
     f.series(:name=>'Jane', :data=> [1, 3, 4, 3, 3, 5, 4,-46,7,8,8,9,9,0,0,9] )
      #renders xml: @employee
     
    
     #f.series(json:@employee_details_with_timesheets)
     #render json:data.to_json
    
    end

    
end

  def index
    @employees = Employee.all
    @timesheets = Timesheet.all
    # render json:@employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.timesheets.build
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end


 def chart
    @h = LazyHighCharts::HighChart.new('line') do |f|
        f.chart({:defaultSeriesType=>'line' , :margin=> [50, 200, 60, 170]} )


      f.series(:name=>'Johnss', :data=>[3, 20, 3, 5, 4, 10, 12 ,3, 5,6,7,7,80,9,9])
     # f.series(:name=>'Jane', :data=> [1, 3, 4, 3, 3, 5, 4,-46,7,8,8,9,9,0,0,9] )
      #render xml: @employee
      f.series(@employee_details_with_timesheets);
    end 
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: [:show, :edit, :update, :destroy]

  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = Timesheet.all
  end

  def view_timesheet_chart 
    start_date= "2008-12-01"
    end_date="2008-12-07"
    @employee_id = params[:id]
    employee_details_with_timesheets =  Timesheet.find_with_timesheets_in_date_range(@employee_id,start_date,end_date)
    if(!employee_details_with_timesheets.nil?)
        @employee_details_with_timesheets =employee_details_with_timesheets[0]
    else
      @employee_details_with_timesheets =nil;
    end
      headers["content-type"]="text/html"
end


  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

def report_hours

  @reportHours = Timesheet.sum(:hours_spent, :group => :employee_id)
  # myjson = @reportHours.collect{|timesheet| :name=>"0", :data=>[10] }.to_json
   
  #render json:myjson


    @h = LazyHighCharts::HighChart.new('bar') do |f|
    f.chart({:defaultSeriesType=>'bar' , :margin=> [50, 200, 60, 170]} )

        f.series(:name=>"0", :data=>[10])
      

       # f.series(json:@reportHours)
end
end



  #render json:@reportHours


  # POST /timesheets
  # POST /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timesheet }
      else
        format.html { render action: 'new' }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1
  # PATCH/PUT /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = Timesheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timesheet_params
      params.require(:timesheet).permit(:log_date, :hours_spent, :employee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
require 'fusioncharts_helper'
include FusionChartsHelper 
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/chart.html.erb
<%= javascript_include_tag "highcharts"%>
<%
# The xml is obtained as a string from builder template.
#str_xml = render :partial =>"timesheet_data",  collection: @employee_details_with_timesheets %>

# Create the chart - Column 3D Chart with data from strXML
<% 
#render_chart  "FusionCharts/Column3D.swf" , "public/Data.xml","", "Timechart" ,  650 ,  400 ,  false, false do %>

<%= high_chart("my_id", @h) %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class ="container">
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>

        <td><%= link_to employee.name, {:action=>'view_timesheet_chart',:id=>employee.id} %></td>

        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      <td><%= link_to 'Time Chart', {:action=>'view_timesheet_chart',:id=>employee.id} %></td>
        <td><%= link_to 'Chart', {:action=>'chart',:id=>employee.id} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</tr>
</div>
<!--%= link_to 'New Employee', new_employee_path %-->

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<%= debug @employee %>
<p>
<b> Title: </b>
<%= @employee.name %>
</p>

<%= simple_format @employee.to_yaml %>
<p>
<b>EMP:</b>
<%= @employee.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/view_timesheet_chart.html.erb
<%= javascript_include_tag "highcharts"%>
<%
# The xml is obtained as a string from builder template.
#str_xml = render :partial =>"timesheet_data",  collection: @employee_details_with_timesheets %>

# Create the chart - Column 3D Chart with data from strXML
<% 
#render_chart  "FusionCharts/Column3D.swf" , "public/Data.xml","", "Timechart" ,  650 ,  400 ,  false, false do %>

<%= high_chart("my_id", @h) %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeTrackerApplication</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

 <%= javascript_include_tag 'highcharts' %> <!--[if IE]> <%= javascript_include_tag 'excanvas.compiled' %> <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>
  <% if @timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% @timesheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :log_date %><br>
    <%= f.datetime_select :log_date %>
  </div>
  <div class="field">
    <%= f.label :hours_spent %><br>
    <%= f.number_field :hours_spent %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timesheets/chart.html.erb
<%= javascript_include_tag "highcharts"%>
<%
# The xml is obtained as a string from builder template.
#str_xml = render :partial =>"timesheet_data",  collection: @employee_details_with_timesheets %>

# Create the chart - Column 3D Chart with data from strXML
<% 
#render_chart  "FusionCharts/Column3D.swf" , "public/Data.xml","", "Timechart" ,  650 ,  400 ,  false, false do %>

<%= high_chart("my_id", @h) %>

app/views/timesheets/edit.html.erb
<h1>Editing timesheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<h1>Listing timesheets</h1>

<table>
  <thead>
    <tr>
      <th>Log date</th>
      <th>Hours spent</th>
      <th>Employee</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= timesheet.log_date %></td>
        <td><%= timesheet.hours_spent %></td>
        <td><%= timesheet.employee_id %></td>
        <td><%= link_to 'Show', timesheet %></td>
        <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
        <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timesheet', new_timesheet_path %>
<%= link_to 'report_hours', {:action=>'report_hours'} %>
<%= link_to 'no_tickets', {:action=>'report_hours'} %>

app/views/timesheets/new.html.erb
<h1>New timesheet</h1>

<%= render 'form' %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/report_hours.html.erb
<%= javascript_include_tag "highcharts"%>
<%
# The xml is obtained as a string from builder template.
#str_xml = render :partial =>"timesheet_data",  collection: @employee_details_with_timesheets %>

# Create the chart - Column 3D Chart with data from strXML
<% 
#render_chart  "FusionCharts/Column3D.swf" , "public/Data.xml","", "Timechart" ,  650 ,  400 ,  false, false do %>

<%= high_chart("my_id", @h) %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Log date:</strong>
  <%= @timesheet.log_date %>
</p>

<p>
  <strong>Hours spent:</strong>
  <%= @timesheet.hours_spent %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @timesheet.employee_id %>
</p>

<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/view_timesheet_chart.html.erb
<%= javascript_include_tag "FusionCharts"%>
<%
# The xml is obtained as a string from builder template.
str_xml = render "employees/timesheet_data"
#Create the chart - Column 3D Chart with data from strXML
render_chart '/FusionCharts/Column3D.swf' , '' , str_xml , 'TimeChart' ,  650 ,  400 ,  false ,  false do -%>

<%  end -%> 